### ISSUE TITLE
"View all results" show hardcoded vars in the content

### ISSUE THREAD

**Issue by ivchee** [courseguide/courseguide#10]
Start typing something in the box  
Instead of hitting Enter, select "View all results" at the bottom 

![screenshot-4](https://cloud.githubusercontent.com/assets/9424379/5469137/01ab1304-85d0-11e4-9eb8-4d54b218b1c3.png)

**Comment by vilianepich** [comment]
This is pretty major, we need to fix it :(

**Comment by ivchee** [comment]
we cant !

**Comment by ivchee** [comment]
not that major !

**Comment by ivchee** [comment]
fixed in : /var/www/html/joomla123/components/com_rssearch/views/results/tmpl/default.php
