### ISSUE TITLE
Home page shows ERR message after log-in 

### ISSUE THREAD

**Issue by dnentchev** [courseguide/courseguide#11]
After I log in I see this red square with ERR message that I am not authorized to see whatever.
I can still do everything after that, but seeing this message may be confusing for outside users.

![image](https://cloud.githubusercontent.com/assets/10204725/5474249/be1c0192-8607-11e4-8c68-868bccf6ffd5.png)

**Comment by ivchee** [comment]
duplicate : https://github.com/courseguide/courseguide/issues/2

**Comment by ivchee** [comment]
fixed by using login redirect plugin...might be the "img" things that we try to access but cant see on windows..(edit profile, logout)
