### ISSUE TITLE
Graphs to be histogram not pie chart

### ISSUE THREAD

**Issue by dnentchev** [courseguide/courseguide#13]
pie charts are not that intuitive when the metric is an average.

Is it possible to turn this into a histogram ?

![image](https://cloud.githubusercontent.com/assets/10204725/5474438/5a62512c-8609-11e4-9765-8b62d483c190.png)

**Comment by ivchee** [comment]
ill check dali izglejda kakto trqbva, no shte trqbva da reinsertna vsichko :) dano neshto ne se schupi...shte probvam dovechera

**Comment by ivchee** [comment]
done
