### ISSUE TITLE
Change scale of voting tool 1-5 (not 0-5)

### ISSUE THREAD

**Issue by dnentchev** [courseguide/courseguide#16]
Several reasons for this:
1) too much options may confuse people
2) 0-5 are 6 possible choices, so there is no middle (neutral) choice
3) GRADE metric does not fit LSE grading scheme if we have 6 options. 
In the UK grading scale is Distinction (5), Merit(4), Pass(3), Fail(2), Bad Fail (1)
So only 5 options.

I suggest we change the scale from 0-5 to 1-5 range.
If possible do not delete existing comments. Noone voted with 0 anyway for now.

**Comment by ivchee** [comment]
changed it on DEV but i was thinking that the order for the graph should be the same as the order of the voting options under it :S

**Comment by ivchee** [comment]
also the votes that are already existing - they will mix with those and the graph will calculate strange results .... which is not that bad :)

**Comment by ivchee** [comment]
`UPDATE feed_modules SET params = REPLACE( params, '\"range_da\":\"0\"', '\"range_da\":\"1\"' ) WHERE id >=1025`

**Comment by ivchee** [comment]
done
