### ISSUE TITLE
Navigation buttons are slightly misaligned/ change colour if possible. 

### ISSUE THREAD

**Issue by vilianepich** [courseguide/courseguide#19]
![screen shot 2014-12-18 at 2 50 28 pm](https://cloud.githubusercontent.com/assets/10232211/5488386/974fbaea-86c5-11e4-9893-8808e596cce8.jpg)

The first button on the homepage is slightly misaligned. The little arrow that it contains at its beggining is cut. 

Also can we change the colour of the buttons as they blend with the background and dont really look as buttons until you hover over them.

**Comment by ivchee** [comment]
changin colors - not possible at this point...no time for research....position - fixed - Grid2  = blank (advanced options) baseline template settings
