### ISSUE TITLE
Make the graph calculate the average not the sum of the votes

### ISSUE THREAD

**Issue by ivchee** [courseguide/courseguide#4]
Currently the graph shows the votes (1-5 votes) in the pie chart.  
We want it to calculate the `average sum(votes)/numer_users_that_voted`  

The module is located in https://github.com/courseguide/courseguide/tree/master/components/com_freevotes and https://github.com/courseguide/courseguide/tree/master/modules/mod_freevotes  

We do not want to see 17 for example but 17/3 (if 3 users have voted)
If we can do something about that, it would be great ! :  

![screenshot-2](https://cloud.githubusercontent.com/assets/9424379/5446760/43ed6764-84bb-11e4-9d22-507eba0a61f9.png)

**Comment by viktorstaikov** [comment]
The fix is committed to master branch. To be uploaded on live. https://github.com/courseguide/courseguide/commit/83db4c2db47fe02a5a6fa002ff96f60104a4715a
