### ISSUE TITLE
home page search box - default text and input options

### ISSUE THREAD

**Issue by dnentchev** [courseguide/courseguide#7]
We need a hint text inside the box to tell the user what he needs to give as input.

Users should be able to either put in Course Name (e.g. Managing Digital Business), or course code (e.g. MG453). And the search engine should be able to find the right course based on that.

**Comment by ivchee** [comment]
deafult text added now : line 105 :  

```
<input type="text" value="Enter a course ID or name..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;" id="rsf_inp<?php echo $module->id;?>"
```

modules/mod_rssearch/tmpl/deault.php
